name: deploy_backend

on:
  push:
    branches:
      - "master"
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          echo "deploying backend"
          ls -l