name: deploy_backend

on:
  workflow_dispatch:
    
  push:
    branches: ["main"]
    
    paths:
      - "Backend/**"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Display Information
        env:
          MY_VAR: ${{secrets.ABS}}
        run: |
          echo "Deploying backend"
          echo "Secret: $MY_VAR+123"  
