name: deploy_backend

on:
  push:
    branches:
      - "master"
    paths:
      - "Backend/**"
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Display Information
        run: |
          echo "deploying backend"
          echo "Secrete : ${{secrets.ABS}}"
          echo "Env : ${{env.ABE}}"