name: Production Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "Infra/**"
      - "Backend/**"
      - "Frontend/**"
env:
  TERRAFORM_WORKING_DIRECTORY: ./Infra
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
        
        run: |
          terraform init \
          -backend-config="resource_group_name=myrg" \
          -backend-config="storage_account_name=mystorage" \
          -backend-config="container_name=terraform" \
          -backend-config="subscription_id=c5544545sfdsdfsd12" \
          -backend-config="tenant_id=5s1f2sf1sdf2ds1" \
          -backend-config="client_id=55131231412468" \
          -backend-config="client_secret=asdfdsfscvsdsndfsd4fsd4f"

# go to your storage account. Under Security + networking, select Access keys
# -backend-config="access_key=${{secrete.access_key}}"


# az role assignment create --assignee <client_Id> --role "Storage Blob Data Contributor" --scope /subscriptions/<your-subscription-id>/resourceGroups/<your-resource-group>/providers/Microsoft.Storage/storageAccounts/<your-storage-account>
