name: Production Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "Infra/**"
      - "Backend/**"
      - "Frontend/**"
env:
  TERRAFORM_WORKING_DIRECTORY: ./Infra
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
        
        run: |
          terraform init \
          -backend-config="resource_group_name=myrg" \
          -backend-config="storage_account_name=mystorage" \
          -backend-config="container_name=terraform"
